### ISSUE TITLE
E714: List Required

### ISSUE THREAD

**Issue by entropitor** [DonnieWest/asyncomplete_neovim_lsp#1]
When I try this plugin, I'm getting the following error:
```
Error executing vim.schedule lua callback: Vim(for):E714: List required
```

I'm using mac os x, neovim v0.5.0-1bfccf028

Any ideas?

**Comment by DonnieWest** [comment]
Could you try testing it with the latest Git HEAD?

**Comment by entropitor** [comment]
I'm still getting the same error there

**Comment by DonnieWest** [comment]
@entropitor sorry for the delay. I'm still not replicating it - could I get a minimal project and a minimal config that you're using here?

Thanks :)

**Comment by DonnieWest** [comment]
This should be resolved now because of help on the linked issue and commit 607d1d986a0a6b874f62095a9512055d47b6f2ab

**Comment by entropitor** [comment]
Ah okay, awesome. I was indeed using `tsserver`, sorry I wanted to carve out some time next week to make a minimal project.
